app:
  rate-booking-duration: 120
  default-base-currency: GBP
  default-additional-pip: 1
  forex-rate-api-url: http://localhost:3000


debug: false
    
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG    
        
       
