app:
  rate-booking-duration: 120
  default-base-currency: GBP
  forex-rate-api-url: https://api.exchangeratesapi.io


debug: false

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        
       
