app:
  rate-booking-duration: 120
  forex-rate-api-url: https://api.exchangeratesapi.io


debug: false

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
        
       
