version: 2.1

orbs:
  sonarcloud: extendaretail/sonarcloud@0.0.2

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    
    working_directory: ~/reactive-spring-forex-trade
      
    steps:
      # get source from git
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - reactive-spring-forex-trade-{{ checksum "pom.xml" }}
          
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: reactive-spring-forex-trade-{{ checksum "pom.xml" }}      
      
      # Compile & Run Unti Test
      - run:
          name: Compile & Run Unit Test
          command: mvn test -P unit-test
      - sonarcloud/scan_with_maven:
          scanner_version: 3.8.0.2131
  test:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            - reactive-spring-forex-trade-{{ checksum "pom.xml" }}    
    
      - run:
          name: Run Integratin Test
          command: mvn test -P integration-test
          
      - run:
          name: Run End-to-End Test
          command: mvn verify -P e2e-test
      
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - sonarcloud/check_quality_gate:
          context: SonarCloud
          requires:
            - build
      - test:
          requires:
            - sonarcloud/check_quality_gate
